[book]
title = "Recipes"
authors = ["Jennifer Pylko"]
description = "good food"
src = "."

[preprocessor.autosummary]
index-name = "category.md"

[output.html]
after = ["autosummary"]
site-url = "/openlore/"
git-repository-url = "https://github.com/JenniferPylko/recipes"
edit-url-template = "https://github.com/JenniferPylko/recipes/edit/main/{path}"
no-section-label = true

[output.html.fold]
enable = true
level = 1

[output.wordcount]
optional = true

[output.linkcheck]
optional = true